# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\MyProjects\Tools_py\sine_wave_generate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.spinBox_samplerate = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_samplerate.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBox_samplerate.setMinimum(8)
        self.spinBox_samplerate.setMaximum(256)
        self.spinBox_samplerate.setObjectName("spinBox_samplerate")
        self.horizontalLayout.addWidget(self.spinBox_samplerate)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.spinBox_amplitude = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_amplitude.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBox_amplitude.setMaximum(32768)
        self.spinBox_amplitude.setSingleStep(1)
        self.spinBox_amplitude.setProperty("value", 4800)
        self.spinBox_amplitude.setObjectName("spinBox_amplitude")
        self.horizontalLayout.addWidget(self.spinBox_amplitude)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.spinBox_cycle = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_cycle.setMaximumSize(QtCore.QSize(100, 16777215))
        self.spinBox_cycle.setMinimum(1)
        self.spinBox_cycle.setMaximum(1024)
        self.spinBox_cycle.setObjectName("spinBox_cycle")
        self.horizontalLayout.addWidget(self.spinBox_cycle)
        self.pushButton_generate = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_generate.setObjectName("pushButton_generate")
        self.horizontalLayout.addWidget(self.pushButton_generate)
        self.pushButton_show = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_show.setObjectName("pushButton_show")
        self.horizontalLayout.addWidget(self.pushButton_show)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "sine_wave_generate"))
        self.label.setText(_translate("MainWindow", "说明：使用SIN( 2 * PI * index / samplerate) * amplitude 生成DAC正弦波数据"))
        self.label_2.setText(_translate("MainWindow", "采样率："))
        self.label_4.setText(_translate("MainWindow", "kHz"))
        self.label_3.setText(_translate("MainWindow", "幅度："))
        self.label_5.setText(_translate("MainWindow", "循环次数："))
        self.pushButton_generate.setText(_translate("MainWindow", "生成数据"))
        self.pushButton_show.setText(_translate("MainWindow", "显示波形"))
